### ISSUE TITLE
Improve autoload

### ISSUE THREAD

**Issue by parf** [lodash-php/lodash-php#1]
Right now your autoload iterate over directory tree and manually includes every file (one function per file)
> find . -name "*.php" | wc -l 
288  FILES = 288 includes
This approach makes this library unusable for any serious system. 

Please create one file with all functions.
You can create build script to generate this file:

suggestion:
vendor/lodash-php/lodash-php/src:
  echo "declare(strict_types=1); namespace _;" > loadash-one-file.php
  find . -name "*.php" | grep -v internal | xargs -n 1 php -w | sed "s/<?php/\r/g" | sed "s/declare(strict_types=1); namespace _;//g" >>  loadash-one-file.php
 .. same for internal/*.php

^^^ this script + minor code fixes will create you one file with all your functions

**Comment by pierredup** [comment]
Yes the autoloading is not optimized at the moment, but it is on the roadmap to be improved before the first stable release. I only did it like that initially to get all the functions included, but it was never going to stay like that. Before the stable release, the autoloading and the `_` will be properly generated
