### ISSUE TITLE
Best way to support chaining

### ISSUE THREAD

**Issue by mgenereu** [lodash-php/lodash-php#11]
As an extension to #8 , I'd like to either document the magic methods with `@method` or replace them with real method calls.  My IDE refuses to do code completion and other features until they're there or in the docblock.  So my question is which of the two would @pierredup prefer.  I always prefer real methods, even if auto-generated by a script, than more magic.

**Comment by mgenereu** [comment]
To clarify, I'd like to do a pull request but I need to know what you want me to code on this.

**Comment by mgenereu** [comment]
@pierredup ?

**Comment by pierredup** [comment]
I think the best would be to auto-generate the methods.
We already have a compile script to compile all the functions into a single file. Part of that script can be to create the methods on the `_` class (it can be generated as a separate class or a trait)

**Comment by mgenereu** [comment]
Thanks for your feedback.  I'll get started on this.

**Comment by j-masci** [comment]
Did this ever get worked on? Some code completion on the global _ class would be nice.
