### ISSUE TITLE
Using with Laravel cause issues

### ISSUE THREAD

**Issue by ermamud** [lodash-php/lodash-php#12]
Using the library with `Laravel` or `Lumen` cause the folowing issue since __ is already being used by the core framework.

```
Fatal error: Cannot redeclare __() (previously declared in ..../vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:947) in ..../vendor/lodash-php/lodash-php/src/compiled.php on line 5
```

Any idea how to fix this issue? Creating a different class name perhaps?

Thank you

**Comment by pierredup** [comment]
I've added a check to only register the `__` function if the name is not already in use.
Updating to the latest commit in master should resolve your issue.

**Comment by shadoWalker89** [comment]
Could you tag it and re compile the compiled file ?

**Comment by phuongnm153** [comment]
Hi,
I have the same issue with Laravel 5.7
When I run this command
`composer require lodash-php/lodash-php`
Then it has a error:
`PHP Fatal error:  Cannot redeclare __() (previously declared in ..\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:947) in .\vendor\lodash-php\lodash-php\src\compiled.php on line 5

Fatal error: Cannot redeclare __() (previously declared in ..\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:947) in .\vendor\lodash-php\lodash-php\src\compiled.php on line 5`
Can you help me?
Thanks

**Comment by pierredup** [comment]
Version [0.0.6](https://github.com/lodash-php/lodash-php/releases/tag/0.0.6) has been released, which includes the fix for this. Please update your composer.json to use `lodash-php/lodash-php: ^0.0.6`
