### ISSUE TITLE
`_\flatten` not expand empty array inside passed array

### ISSUE THREAD

**Issue by tooppoo** [lodash-php/lodash-php#13]
when I pass `_\flatten` an array which contains empty array, `_\flatten` does not expand the empty array.

ex.
```
use function _\flatten;

$arr = [
    [1, 2, 3],
    [],
    [4, 5, 6],
];
$result = flatten($arr);
```

I expected that `$result` is `[1, 2, 3, 4, 5, 6]`, but actually `[1, 2, 3, [], 4, 5, 6]`.

this behavior is expected?

**Comment by pierredup** [comment]
Thanks @tooppoo, this is now fixed in the master branch
