### ISSUE TITLE
Lack of defaultTo - porting proposal

### ISSUE THREAD

**Issue by punit-kulal** [lodash-php/lodash-php#18]
I couldn't find the defaultTo function present in the lodash JS
I could create a pull request for the same 
The defafultTo function signature would be as follows:
_::defaultTo(object|associative array, string|array, defaultValue[, defaultToOnEmpty])

**Comment by pierredup** [comment]
Thank you @punit-kulal, you are welcome to send a pull request. Let me know if you need any assistance

**Comment by punit-kulal** [comment]
done
