### ISSUE TITLE
Call to undefined function `_\\get()`

### ISSUE THREAD

**Issue by geoidesic** [lodash-php/lodash-php#23]
I'm struggling to get this library to work. 

I've required it via composer. I'm trying to include it with a class (none of the examples in the docs show how to work within classes).

composer.json
```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "lodash-php/lodash-php": "^0.0.6",
```

php code
```
<?php
namespace App\Controller\Api;
use function _\get;
class Controller{
    public function __construct()
    {
        get('one.two.three');
    }
```
error:
```
 {
            "status": "500",
            "title": "Internal Server Error",
            "detail": "Call to undefined function _\\get()"
 }
```

I tried this without using classes and I get the same error:
```
<?php
namespace App\Controller\Api;
use function _\get;
get('obj.one.two.three');
die();
```
error: `Call to undefined function _\\get()`

Update: it seems other functions are working, it's only `get` that doesn't (Murphy's law because that's the only function I'm interested in!).

Looking through the vendor src folder I can see that the get function is not included. The README seems to indicate that it would be expected in the `Objects` folder but it is not present there.

 I also tried `composer remove` and then `require` again. Same deal, `src/Objects/get.php` is missing. I'm on Mac OS X Catalina and Composer version 1.8.6

I also notice that the tests for `get` are missing from the tests folder.

**Comment by geoidesic** [comment]
I tried this without using classes and I get the same error:
```
<?php
namespace App\Controller\Api;
use function _\get;
$obj = [
    'one' => [
        'two' => [
            'three' => 3,
        ],
    ],
];
get('obj.one.two.three');
die();
```

**Comment by geoidesic** [comment]
Update: it seems other functions are working, it's only `get` that doesn't (Murphy's law because that's the only function I'm interested in!).

Looking through the vendor src folder I can see that the get function is not included. The README seems to indicate that it would be expected in the `Objects` folder but it is not present there.

**Comment by geoidesic** [comment]
I also tried `composer remove` and then `require` again. Same deal, `src/Objects/get.php` is missing. I'm on Mac OS X Catalina and Composer version 1.8.6

**Comment by gedsonmarcelino** [comment]
Unfortunately,  the version 0.0.6 doesn't have the function **get**, but if you get from master branch it will be there.

**Comment by minasvisual** [comment]
I solve it to this way.

$company = [
	'departments' => [
		['teste' => "teste result"],
		['teste2' => "teste result 2"]
	]
];

function get($data, $string, $default = null){
  $arrStr = explode('.', $string);
  $result = $data;
  foreach($arrStr as $lvl){
    if( isset($result[$lvl]) ) $result = $result[$lvl];
    else $result = $default; 
  }
  return $result;
}

echo get($company, 'departments.0.teste', 'default');

**Comment by cube-dan** [comment]
To get _::get() and get() do this: 

1) setup your composer.json like this:
```json
{
    ...
    "require": {
       ...
        "lodash-php/lodash-php": "dev-master",
       ...
    },
    "repositories": [
      {
        "type": "vcs",
        "url": "https://github.com/lodash-php/lodash-php.git"
      }
    ]
    ...
}
```
2) run `composer update`

Thanks @gedsonmarcelino for [the hint](https://github.com/lodash-php/lodash-php/issues/23#issuecomment-598761834)!

**Comment by pierredup** [comment]
Version [0.0.7](https://github.com/lodash-php/lodash-php/releases/tag/0.0.7) has now been tagged, which includes the `get` function.

**Comment by cube-dan** [comment]
Thanks for adding the 0.0.7 tag @pierredup.
