### ISSUE TITLE
can't install for laravel 8

### ISSUE THREAD

**Issue by developer-ssr** [lodash-php/lodash-php#27]
Hi I'm having an issue installing this to laravel 8

![Capture](https://user-images.githubusercontent.com/49543192/98778347-2b172f00-242d-11eb-9b5d-041013939fc3.PNG)

**Comment by LajnaLegenden** [comment]
Hey

I fixed this by using the master branch in composer like so 
`    "repositories": [{
        "type": "vcs",
        "url": "https://github.com/lodash-php/lodash-php"
    }],`

`        "lodash-php/lodash-php": "dev-master",
`
This pulls the code direct from master, so you can fork and keep your own modified version untill its updated.

**Comment by pierredup** [comment]
Version [0.0.7](https://github.com/lodash-php/lodash-php/releases/tag/0.0.7) has now been tagged which should solve this issue.
