### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tchari** [lodash-php/lodash-php#28]
Release 0.0.7 was over a year ago and uses now abandoned packages.

(Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.)

**Comment by pierredup** [comment]
I haven't had much interest in maintaining this project over the last couple of years. It's not officially abandoned, I just personally haven't used it, so haven't found much time to keep it up to date. I still welcome any contributions, and if there is a strong need to use this package, then I can still continue keeping it up to date, but only if there is enough interest.
