### ISSUE TITLE
Incorrect tag on release

### ISSUE THREAD

**Issue by crazycodr** [lodash-php/lodash-php#44]
You release 0.09 instead of 0.0.9 @pierredup ...

Why isn't it a 1.x tag anyway. This has been out for multiple years and works no?

**Comment by samandeggs** [comment]
+1 is not great, maybe fix with a 1.0.0 release as @crazycodr suggests

**Comment by pierredup** [comment]
I created a new correct tag 0.0.9. https://github.com/lodash-php/lodash-php/releases/tag/0.0.9

> Why isn't it a 1.x tag anyway. This has been out for multiple years and works no?

There are still a lot of functions missing, which is why I don't want to tag 1.0.0 yet. I might go with a 0.1.0 release soon, and when all the missing functions are added, then it can go to 1.0.0
