### ISSUE TITLE
Namespace issue with using 'chain' method

### ISSUE THREAD

**Issue by birdiewd** [lodash-php/lodash-php#9]
**Code:**

```
$visibleColumns = \_::chain($columnSettings)
	->filter(function($column) {
		return
			null == $columns['ratioCalculations'] &&
			null == $columns['averageCalculation'] &&
			null == $columns['percentageOf']
		;
	})
	->map(function($column) {
		return [
			$columns['name'],
			$columns['alt_name'],
		];
	})
	->value();
```

**Error:**

Attempted to call function "chain" from namespace "_".

Symfony\Component\Debug\Exception\
UndefinedFunctionException
in vendor/lodash-php/lodash-php/src/Lodash.php (line 56)

```
* @return mixed     
* @throws Exception     
*/
public static function __callStatic(string $method, array $args)    
{
	return ("_\\$method")(...$args);    
}
```

**Comment by pierredup** [comment]
@birdiewd Can you please try with the master branch? It seems you might have an older version of Lodash-PHP installed (Ensure you have `'lodash-php/lodash-php": "dev-master"` in your composer.json)

**Comment by pierredup** [comment]
Version [0.0.5](https://github.com/lodash-php/lodash-php/releases/tag/0.0.5) has been released which includes the `chain` function
